# Regenerates manifest.js by scanning assets/images/<project>/<category>/ folders
# for image files. Run this any time you add, remove, or reorder images.
#
# Usage (from project root or this folder):
#   powershell -ExecutionPolicy Bypass -File assets/images/generate-manifests.ps1
#
# Images within a folder are sorted naturally (1.jpg, 2.jpg, ... 10.jpg), so name
# them in the order you want them to appear in the carousel.

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $MyInvocation.MyCommand.Path
$imageExts = @('.jpg', '.jpeg', '.png', '.webp', '.gif', '.avif')

$manifest = [ordered]@{}

Get-ChildItem -Path $root -Directory | Sort-Object Name | ForEach-Object {
    $projectDir = $_
    Get-ChildItem -Path $projectDir.FullName -Directory | Sort-Object Name | ForEach-Object {
        $categoryDir = $_
        $files = @(
            Get-ChildItem -Path $categoryDir.FullName -File |
                Where-Object { $imageExts -contains $_.Extension.ToLower() } |
                Sort-Object { [regex]::Replace($_.BaseName, '\d+', { param($m) $m.Value.PadLeft(10, '0') }) } |
                Select-Object -ExpandProperty Name
        )
        $key = "assets/images/$($projectDir.Name)/$($categoryDir.Name)"
        $manifest[$key] = $files
    }
}

$json = $manifest | ConvertTo-Json -Depth 4
$output = "// Auto-generated by generate-manifests.ps1 -- do not edit by hand.`nwindow.IMAGE_MANIFEST = $json;`n"
Set-Content -Path (Join-Path $root 'manifest.js') -Value $output -Encoding utf8

$total = ($manifest.Values | ForEach-Object { $_.Count } | Measure-Object -Sum).Sum
Write-Host "Generated manifest.js -- $($manifest.Count) folders, $total images total."
