# Regenerates manifest.js by scanning assets/videos/<project>/<category>/ folders
# for video files. Run this any time you add, remove, or reorder videos.
#
# Usage (from project root or this folder):
#   powershell -ExecutionPolicy Bypass -File assets/videos/generate-manifests.ps1
#
# Videos within a folder are sorted naturally (1.mp4, 2.mp4, ... 10.mp4), so name
# them in the order you want them to appear.

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $MyInvocation.MyCommand.Path
$videoExts = @('.mp4', '.webm', '.mov', '.m4v', '.ogv')

$manifest = [ordered]@{}

Get-ChildItem -Path $root -Directory | Sort-Object Name | ForEach-Object {
    $projectDir = $_
    Get-ChildItem -Path $projectDir.FullName -Directory | Sort-Object Name | ForEach-Object {
        $categoryDir = $_
        $files = @(
            Get-ChildItem -Path $categoryDir.FullName -File |
                Where-Object { $videoExts -contains $_.Extension.ToLower() } |
                Sort-Object { [regex]::Replace($_.BaseName, '\d+', { param($m) $m.Value.PadLeft(10, '0') }) } |
                Select-Object -ExpandProperty Name
        )
        $key = "assets/videos/$($projectDir.Name)/$($categoryDir.Name)"
        $manifest[$key] = $files
    }
}

$json = $manifest | ConvertTo-Json -Depth 4
$output = "// Auto-generated by generate-manifests.ps1 -- do not edit by hand.`nwindow.VIDEO_MANIFEST = $json;`n"
Set-Content -Path (Join-Path $root 'manifest.js') -Value $output -Encoding utf8

$total = ($manifest.Values | ForEach-Object { $_.Count } | Measure-Object -Sum).Sum
Write-Host "Generated manifest.js -- $($manifest.Count) folders, $total videos total."
